### ISSUE TITLE
Generic Read

### ISSUE THREAD

**Issue by bbarker** [purescript/purescript-generics-rep#33]
I know that [Read](https://pursuit.purescript.org/packages/purescript-read/1.0.1/docs/Data.String.Read#v:read) is generally frowned on but it does have its uses. Doing something like what is described for [Enum types in JSON,](https://purescript-simple-json.readthedocs.io/en/latest/generics-rep.html#working-with-enum-sum-types) but just for a regular-old string-based `Read`, for instance. I briefly tried my hand at this but got lost somewhere around trying to convert the `ExceptT` into something resembling a (possibly wrapped) `Maybe a`.

I'll note here that this appears to be different that what is provided in `Rep.Enum`, which is a more literal interpretation of enumerations, rather than conversion between strings and nullary constructor values. But this is just one example.

**Comment by hdgarrood** [comment]
Read is difficult for us because there are so many non-derived Show instances floating around; because of this (and also because it’s not really something you should be doing anyway) I’d rather not incorporate it into the core libraries. It should be possible to implement in a separate library though.

**Comment by bbarker** [comment]
Yes, I see what you mean - just the other day I had to come up with a partially-derived `show` for a enum-like data type. I liked that I could do that, using pattern matching, but it could get messy quickly keeping it all sorted.
